services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Sylius:/var/www/html/back:delegated
    depends_on:
      - front
      - back
    networks:
      - sylius

  front:
    build:
      context: ./FrontWing
      dockerfile: .docker/dev/Dockerfile
    volumes:
      - ./FrontWing:/var/www/html/front
    working_dir: /var/www/html/front
    tty: true
    command: ["/bin/sh", "-c", "npm install && npm run dev"]
    expose:
      - "5173"
    networks:
      - sylius

  back:
    build:
      context: ./Sylius/.docker/dev
    environment:
      APP_ENV: "dev"
      DATABASE_URL: "mysql://root:mysql@mysql/sylius_%kernel.environment%?charset=utf8mb4"
      PHP_DATE_TIMEZONE: "Europe/Warsaw"
      PHP_XDEBUG_IDEKEY: "PHPSTORM"
      MAILER_URL: "smtp://mailhog:1025"
    volumes:
      - ./Sylius:/var/www/html/back:delegated
      - ./Sylius/.docker/dev/php.ini:/usr/local/etc/php/conf.d/custom.ini:delegated
    depends_on:
      - mysql
    expose:
      - "9000"
    networks:
      - sylius

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sylius

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - sylius

networks:
  sylius:
    driver: bridge

volumes:
  mysql_data:
